services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway-migrate:
    build: .
    env_file: .env

  gateway:
    build: .
    env_file: .env

  gateway_db:
    ports:
      - "5432:5432"

  gateway-redis:
    ports:
      - "6379:6379"

networks:
  internal:
    internal: false
