services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - rabbit_net

  gateway-migrate:
    build: .
    command: alembic upgrade head # sovrascrive il comando di avvio eseguendo solo le migrazioni
    depends_on:
      - gateway_db
    networks:
      - gateway_net
    deploy:
      replicas: 1 # forza una sola istanza
    restart: "no" # non viene riavviato

  gateway:
    build: .
    command: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000 --workers 1
    ports:
      - "8000:8000"
    depends_on:
      gateway_db:
        condition: service_started
      gateway-migrate:
        condition: service_completed_successfully
    networks:
      - gateway_net
      - rabbit_net
      - internal
    restart: unless-stopped

  gateway_db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gateway
    volumes:
      - gateway_db_data:/var/lib/postgresql/data
    networks:
      - gateway_net
    restart: unless-stopped

  gateway-redis:
    image: redis:7.4-alpine
    container_name: gateway-redis
    command: >
      redis-server  --requirepass ${GATEWAY_REDIS_PASSWORD}  --appendonly yes  --rename-command FLUSHALL ""  --rename-command CONFIG ""  --rename-command KEYS ""
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${GATEWAY_REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gateway_db_data:


networks:
  gateway_net:
  rabbit_net:
    driver: bridge
  internal:
    driver: bridge
    internal: true
